// Episode titles are stored separately from the main catalog so the tracker data stays easy to maintain.
// Titles are in broadcast order within each season.
window.MCU_EPISODE_TITLES = {
  "series-01": [
    "Filmed Before a Live Studio Audience",
    "Don't Touch That Dial",
    "Now in Color",
    "We Interrupt This Program",
    "On a Very Special Episode…",
    "All-New Halloween Spooktacular!",
    "Breaking the Fourth Wall",
    "Previously On",
    "The Series Finale"
  ],
  "series-02": [
    "New World Order",
    "The Star Spangled Man",
    "Power Broker",
    "The Whole World Is Watching",
    "Truth",
    "One World, One People"
  ],
  "series-03": [
    "Glorious Purpose",
    "The Variant",
    "Lamentis",
    "The Nexus Event",
    "Journey Into Mystery",
    "For All Time. Always."
  ],
  "series-04": [
    "What If… Captain Carter Were the First Avenger?",
    "What If… T'Challa Became a Star-Lord?",
    "What If... The World Lost its Mightiest Heroes?",
    "What If… Doctor Strange Lost His Heart Instead of His Hands?",
    "What If... Zombies!?",
    "What If… Killmonger Rescued Tony Stark?",
    "What If… Thor Were an Only Child?",
    "What If... Ultron Won?",
    "What If... The Watcher Broke His Oath?"
  ],
  "series-05": [
    "Never Meet Your Heroes",
    "Hide and Seek",
    "Echoes",
    "Partners, Am I Right?",
    "Ronin",
    "So This Is Christmas?"
  ],
  "series-06": [
    "The Goldfish Problem",
    "Summon the Suit",
    "The Friendly Type",
    "The Tomb",
    "Asylum",
    "Gods and Monsters"
  ],
  "series-07": [
    "Generation Why",
    "Crushed",
    "Destined",
    "Seeing Red",
    "Time and Again",
    "No Normal"
  ],
  "series-08": [
    "A Normal Amount of Rage",
    "Superhuman Law",
    "The People vs. Emil Blonsky",
    "Is This Not Real Magic?",
    "Mean, Green, and Straight Poured into These Jeans",
    "Just Jen",
    "The Retreat",
    "Ribbit and Rip it",
    "Whose Show Is This?"
  ],
  "series-09": [
    "Resurrection",
    "Promises",
    "Betrayed",
    "Beloved",
    "Harvest",
    "Home"
  ],
  "series-10": [
    "Ouroboros",
    "Breaking Brad",
    "1893",
    "Heart of the TVA",
    "Science/Fiction",
    "Glorious Purpose"
  ],
  "series-11": [
    "What If... Nebula Joined the Nova Corps?",
    "What If... Peter Quill Attacked Earth's Mightiest Heroes?",
    "What If... Happy Hogan Saved Christmas?",
    "What If... Iron Man Crashed into the Grandmaster?",
    "What If... Captain Carter Fought the Hydra Stomper?",
    "What If... Kahhori Reshaped the World?",
    "What If... Hela Found the Ten Rings?",
    "What If... The Avengers Assembled in 1602?",
    "What If... Strange Supreme Intervened?"
  ],
  "series-12": ["Chafa", "Lowak", "Tuklo", "Taloa", "Maya"],
  "series-13": [
    "Seekest Thou the Road",
    "Circle Sewn with Fate Unlock Thy Hidden Gate",
    "Through Many Miles of Tricks and Trials",
    "If I Can't Reach You Let My Song Teach You",
    "Darkest Hour, Wake Thy Power",
    "Familiar by Thy Side",
    "Death's Hand in Mine",
    "Follow Me My Friend To Glory at the End",
    "Maiden Mother Crone"
  ],
  "series-14": [
    "What If... The Hulk Fought the Mech Avengers?",
    "What If... Agatha Went to Hollywood?",
    "What If... The Red Guardian Stopped the Winter Soldier?",
    "What If... Howard the Duck Got Hitched?",
    "What If... The Emergence Destroyed the Earth?",
    "What If... 1872?",
    "What If... The Watcher Disappeared?",
    "What If... What If?"
  ],
  "series-15": [
    "Heaven's Half Acre",
    "Optics",
    "The Hollow of His Hand",
    "Sic Semper Tyrannis",
    "With Interest",
    "Excessive Force",
    "Art for Art's Sake",
    "Isle of Joy",
    "Straight to Hell"
  ],
  "series-17": [
    "Into the Lion's Den",
    "Legends and Lies",
    "Lost and Found",
    "The Last Panther"
  ],
  "series-18": ["Episode 1", "Episode 2", "Episode 3", "Episode 4"],
  "series-22": [
    "Now Is Not the End",
    "Bridge and Tunnel",
    "Time and Tide",
    "The Blitzkrieg Button",
    "The Iron Ceiling",
    "A Sin to Err",
    "Snafu",
    "Valediction"
  ],
  "series-23": [
    "The Lady in the Lake",
    "A View in the Dark",
    "Better Angels",
    "Smoke & Mirrors",
    "The Atomic Job",
    "Life of the Party",
    "Monsters",
    "The Edge of Mystery",
    "A Little Song and Dance",
    "Hollywood Ending"
  ],
  "series-31": [
    "Into the Ring",
    "Cut Man",
    "Rabbit in a Snowstorm",
    "In the Blood",
    "World on Fire",
    "Condemned",
    "Stick",
    "Shadows in the Glass",
    "Speak of the Devil",
    "Nelson v. Murdock",
    "The Path of the Righteous",
    "The Ones We Leave Behind",
    "Daredevil"
  ],
  "series-33": [
    "Bang",
    "Dogs to a Gunfight",
    "New York's Finest",
    "Penny and Dime",
    "Kinbaku",
    "Regrets Only",
    "Semper Fidelis",
    "Guilty as Sin",
    "Seven Minutes in Heaven",
    "The Man in the Box",
    ".380",
    "The Dark at the End of the Tunnel",
    "A Cold Day in Hell's Kitchen"
  ],
  "series-41": [
    "Resurrection",
    "Please",
    "No Good Deed",
    "Blindsided",
    "The Perfect Game",
    "The Devil You Know",
    "Aftermath",
    "Upstairs/Downstairs",
    "Revelations",
    "Karen",
    "Reunion",
    "One Last Shot",
    "A New Napkin"
  ],
  "series-32": [
    "AKA Ladies Night",
    "AKA Crush Syndrome",
    "AKA It's Called Whiskey",
    "AKA 99 Friends",
    "AKA The Sandwich Saved Me",
    "AKA You're a Winner!",
    "AKA Top Shelf Perverts",
    "AKA WWJD?",
    "AKA Sin Bin",
    "AKA 1,000 Cuts",
    "AKA I've Got the Blues",
    "AKA Take a Bloody Number",
    "AKA Smile"
  ],
  "series-38": [
    "AKA Start at the Beginning",
    "AKA Freak Accident",
    "AKA Sole Survivor",
    "AKA God Help the Hobo",
    "AKA The Octopus",
    "AKA Facetime",
    "AKA I Want Your Cray Cray",
    "AKA Ain't We Got Fun",
    "AKA Shark in the Bathtub, Monster in the Bed",
    "AKA Pork Chop",
    "AKA Three Lives and Counting",
    "AKA Pray for My Patsy",
    "AKA Playland"
  ],
  "series-43": [
    "A.K.A The Perfect Burger",
    "A.K.A You're Welcome",
    "A.K.A I Have No Spleen",
    "A.K.A Customer Service is Standing By",
    "A.K.A I Wish",
    "A.K.A Sorry Face",
    "A.K.A The Double Half-Wappinger",
    "A.K.A Camera Friendly",
    "A.K.A I Did Something Today",
    "A.K.A Hero Pants",
    "A.K.A Hellcat",
    "A.K.A A Lotta Worms",
    "A.K.A Everything"
  ],
  "series-34": [
    "Moment of Truth",
    "Code of the Streets",
    "Who's Gonna Take the Weight?",
    "Step in the Arena",
    "Just to Get a Rep",
    "Suckas Need Bodyguards",
    "Manifest",
    "Blowin' Up the Spot",
    "DWYCK",
    "Take It Personal",
    "Now You're Mine",
    "Soliloquy of Chaos",
    "You Know My Steez"
  ],
  "series-39": [
    "Soul Brother #1",
    "Straighten It Out",
    "Wig Out",
    "I Get Physical",
    "All Souled Out",
    "The Basement",
    "On and On",
    "If It Ain't Rough, It Ain't Right",
    "For Pete's Sake",
    "The Main Ingredient",
    "The Creator",
    "Can't Front on Me",
    "They Reminisce Over You"
  ],
  "series-35": [
    "Snow Gives Way",
    "Shadow Hawk Takes Flight",
    "Rolling Thunder Cannon Punch",
    "Eight Diagram Dragon Palm",
    "Under Leaf Pluck Lotus",
    "Immortal Emerges from Cave",
    "Felling Tree with Roots",
    "The Blessing of Many Fractures",
    "The Mistress of All Agonies",
    "Black Tiger Steals Heart",
    "Lead Horse Back to Stable",
    "Bar the Big Boss",
    "Dragon Plays with Fire"
  ],
  "series-40": [
    "The Fury of Iron Fist",
    "The City's Not for Burning",
    "This Deadly Secret...",
    "Target: Iron Fist",
    "Heart of the Dragon",
    "The Dragon Dies at Dawn",
    "Morning of the Mindstorm",
    "Citadel on the Edge of Vengeance",
    "War Without End",
    "A Duel of Iron"
  ],
  "series-36": [
    "The H Word",
    "Mean Right Hook",
    "Worst Behavior",
    "Royal Dragon",
    "Take Shelter",
    "Ashes, Ashes",
    "Fish in the Jailhouse",
    "The Defenders"
  ],
  "series-37": [
    "3 AM",
    "Two Dead Men",
    "Kandahar",
    "Resupply",
    "Gunner",
    "The Judas Goat",
    "Crosshairs",
    "Cold Steel",
    "Front Toward Enemy",
    "Virtue of the Vicious",
    "Danger Close",
    "Home",
    "Memento Mori"
  ],
  "series-42": [
    "Roadhouse Blues",
    "Fight or Flight",
    "Trouble the Water",
    "Scar Tissue",
    "One-Eyed Jacks",
    "Nakazat",
    "One Bad Day",
    "My Brother's Keeper",
    "Flustercluck",
    "The Dark Hearts of Men",
    "The Abyss",
    "Collision Course",
    "The Whirlwind"
  ],
  "series-44": [
    "Behold... The Inhumans",
    "Those Who Would Destroy Us",
    "Divide and Conquer",
    "Make Way for... Medusa",
    "Something Inhuman This Way Comes",
    "The Gentleman's Name Is Gorgon",
    "Havoc in the Hidden Land",
    "... And Finally: Black Bolt"
  ],
  "series-45": [
    "Reunion",
    "Rewind",
    "Destiny",
    "Fifteen",
    "Kingdom",
    "Metamorphosis",
    "Refraction",
    "Tsunami",
    "Doomsday",
    "Hostile"
  ],
  "series-46": [
    "Gimme Shelter",
    "Radio On",
    "Double Zeros",
    "Old School",
    "Rock Bottom",
    "Bury Another",
    "Last Rites",
    "Past Life",
    "Big Shot",
    "Hostile Takeover",
    "Last Waltz",
    "Earth Angel",
    "Split Up"
  ],
  "series-47": [
    "Smoke and Mirrors",
    "The Great Escape",
    "Lord of Lies",
    "Rite of Thunder",
    "Enter the Dreamland",
    "Merry Meet Again",
    "Left-Hand Path",
    "Devil's Torture Chamber",
    "The Broken Circle",
    "Cheat the Gallows"
  ],
  "series-48": [
    "First Light",
    "Suicide Sprints",
    "Stained Glass",
    "Call/Response",
    "Princeton Offense",
    "Funhouse Mirrors",
    "Lotus Eaters",
    "Ghost Stories",
    "Back Breaker",
    "Colony Collapse"
  ],
  "series-49": [
    "Restless Energy",
    "White Lines",
    "Shadow Selves",
    "Rabbit Hold",
    "Alignment Chart",
    "B Sides",
    "Vikingtown Sound",
    "Two Player",
    "Blue Note",
    "Level Up"
  ],
  "series-50": [
    "Groot's First Steps",
    "The Little Guy",
    "Groot's Pursuit",
    "Groot Takes a Bath",
    "Magnum Opus"
  ],
  "series-51": [
    "Are You My Groot?",
    "Groot Noses Around",
    "Groot's Sweet Treat",
    "Groot's Kitchen",
    "Groot and the Great Prophecy"
  ],
  "series-24": [
    "Pilot",
    "0-8-4",
    "The Asset",
    "Eye Spy",
    "Girl in the Flower Dress",
    "FZZT",
    "The Hub",
    "The Well",
    "Repairs",
    "The Bridge",
    "The Magical Place",
    "Seeds",
    "T.R.A.C.K.S.",
    "T.A.H.I.T.I.",
    "Yes Men",
    "End of the Beginning",
    "Turn, Turn, Turn",
    "Providence",
    "The Only Light in the Darkness",
    "Nothing Personal",
    "Ragtag",
    "Beginning of the End"
  ],
  "series-25": [
    "Shadows",
    "Heavy Is the Head",
    "Making Friends and Influencing People",
    "Face My Enemy",
    "A Hen in the Wolf House",
    "A Fractured House",
    "The Writing on the Wall",
    "The Things We Bury",
    "...Ye Who Enter Here",
    "What They Become",
    "Aftershocks",
    "Who You Really Are",
    "One of Us",
    "Love in the Time of HYDRA",
    "One Door Closes",
    "Afterlife",
    "Melinda",
    "The Frenemy of My Enemy",
    "The Dirty Half Dozen",
    "Scars",
    "S.O.S.: Part 1",
    "S.O.S.: Part 2"
  ],
  "series-26": [
    "Laws of Nature",
    "Purpose in the Machine",
    "A Wanted (Inhu)man",
    "Devils You Know",
    "4,722 Hours",
    "Among Us Hide…",
    "Chaos Theory",
    "Many Heads, One Tale",
    "Closure",
    "Maveth",
    "Bouncing Back",
    "The Inside Man",
    "Parting Shot",
    "Watchdogs",
    "Spacetime",
    "Paradise Lost",
    "The Team",
    "The Singularity",
    "Failed Experiments",
    "Emancipation",
    "Absolution",
    "Ascension"
  ],
  "series-27": [
    "The Ghost",
    "Meet the New Boss",
    "Uprising",
    "Let Me Stand Next to Your Fire",
    "Lockup",
    "The Good Samaritan",
    "Deals with Our Devils",
    "The Laws of Inferno Dynamics",
    "Broken Promises",
    "The Patriot",
    "Wake Up",
    "Hot Potato Soup",
    "BOOM",
    "The Man Behind the Shield",
    "Self Control",
    "What If...",
    "Identity and Change",
    "No Regrets",
    "All the Madame's Men",
    "Farewell, Cruel World!",
    "The Return",
    "World's End"
  ],
  "series-28": [
    "Orientation (Part One)",
    "Orientation (Part Two)",
    "A Life Spent",
    "A Life Earned",
    "Rewind",
    "Fun & Games",
    "Together or Not at All",
    "The Last Day",
    "Best Laid Plans",
    "Past Life",
    "All the Comforts of Home",
    "The Real Deal",
    "Principia",
    "The Devil Complex",
    "Rise and Shine",
    "Inside Voices",
    "The Honeymoon",
    "All Roads Lead…",
    "Option Two",
    "The One Who Will Save Us All",
    "The Force of Gravity",
    "The End"
  ],
  "series-29": [
    "Missing Pieces",
    "Window of Opportunity",
    "Fear and Loathing on the Planet of Kitson",
    "Code Yellow",
    "The Other Thing",
    "Inescapable",
    "Toldja",
    "Collision Course (Part I)",
    "Collision Course (Part II)",
    "Leap",
    "From the Ashes",
    "The Sign",
    "New Life"
  ],
  "series-30": [
    "The New Deal",
    "Know Your Onions",
    "Alien Commies from the Future!",
    "Out of the Past",
    "A Trout in the Milk",
    "Adapt or Die",
    "The Totally Excellent Adventures of Mack and the D",
    "After, Before",
    "As I Have Always Been",
    "Stolen",
    "Brand New Day",
    "The End Is at Hand",
    "What We're Fighting For"
  ]
};
